# Generated by Django 3.2.7 on 2021-12-02 22:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0004_auto_20211118_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=40)),
                ('eventDescription', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('authorPage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.pages')),
            ],
        ),
    ]
