# Generated by Django 3.2.7 on 2021-12-04 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='eventDate',
            field=models.DateField(default=datetime.date(2021, 12, 4)),
        ),
        migrations.AddField(
            model_name='events',
            name='eventTime',
            field=models.TimeField(default=datetime.time(7, 11, 3, 684180)),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventDescription',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
