# Generated by Django 3.2.7 on 2021-12-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20211204_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='eventDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventTime',
            field=models.TimeField(),
        ),
    ]
