# Generated by Django 3.2.7 on 2021-11-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='followersCount',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='pageDecription',
        ),
        migrations.AddField(
            model_name='pages',
            name='pageDescription',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
