# Generated by Django 3.2.7 on 2021-11-18 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20211118_0259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='id',
            new_name='identifier',
        ),
    ]
