# Generated by Django 3.2.7 on 2021-11-18 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('pages', '0003_rename_id_followers_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='followers',
            name='pageName',
            field=models.ForeignKey(db_column='pageName', on_delete=django.db.models.deletion.CASCADE, to='pages.pages'),
        ),
        migrations.AlterField(
            model_name='followers',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
