# Generated by Django 3.2.7 on 2021-12-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20211118_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='user_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
