# Generated by Django 3.2.7 on 2021-12-02 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('pages', '0006_auto_20211202_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='pageAuthor',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
