# Generated by Django 3.2.7 on 2021-12-02 21:19

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20211202_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='pageAuthor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=profiles.models.Profile),
        ),
    ]
