# Generated by Django 3.2.7 on 2021-12-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_pages_pageauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='pageAuthor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='accounts.UserAccount'),
        ),
    ]
