# Generated by Django 3.2.7 on 2021-12-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_pages_pageauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='user_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
