# Generated by Django 3.2.7 on 2021-12-09 06:25

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_followers_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='pageAuthor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=accounts.models.UserAccount),
        ),
    ]
