# Generated by Django 3.2.7 on 2021-12-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, default='user-ARwSS5F82R1kEbdmlNKg', max_length=220),
        ),
    ]
