# Generated by Django 3.2.7 on 2021-12-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, default='user-uKkJdaL4qpERvm2qHLZX', max_length=220),
        ),
    ]
