# Generated by Django 3.2.7 on 2021-12-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, default='user-okbkEjvKA9NPUB3u3MHk', max_length=220),
        ),
    ]
