# Generated by Django 3.2.7 on 2021-12-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, default='user-y4DIvbX7ZgKgIDU6Cn9E', max_length=220),
        ),
    ]
